### PR TITLE
Replace entity_state_attributes with extra_state_attributes + Removed deprecated properties and added percentage support

### PR DESCRIPTION
**Pull request by mariuske**
Replace entity_state_attributes with extra_state_attributes to stop warning log lines after upgrade to 2021.4 (or later)

### CODE REVIEW

**Comment by mariuske** [comment]
These changes have only been tested on my 4 Flexit Roomie Dual fans.

Disclaimer: I'm not a developer

**Comment by itkama** [comment]
@mariuske is this working for you? If yes, how did you get it working in home assistant? I'm trying to integrate some Blauberg fans which seem to be basically the same as those Flexit fans.

**Comment by mariuske** [comment]
Yes, with these changes it works perfectly with my fans. Please replace the two files linked in this PR and you should be good. The setup is the same as described in the readme of the repo.

For lovelace I'm using the [Fan Percent Button Row](https://github.com/finity69x2/fan-percent-button-row) repo.

**Comment by mariuske** [comment]
@aglehmann - Would you consider to grant me a maintain or admin role for this repository? I have some ideas on how to improve it. Thank you.

**Comment by itkama** [comment]
@mariuske might also want to look at what @gody01 [is doing](https://github.com/gody01/ecovent_v2). There is also [this one](https://github.com/dingusdk/ha-dukaone) here, that works pretty well for me with Blauberg Fans. The one from @gody01 will have more features once he is finished I think.

**Comment by gody01** [comment]
Hello,

My integration unfortunately don't support fans with v1 api firmware. At lest for now.

**Pull request merged**
